# 草稿本

## 不想开matlab导致的

In [1]:
import numpy as np

A = np.array([[-5, 2, -1],
              [ 1, 0,  3],
              [ 3, 1,  6]], dtype=float)

try:
    from scipy.linalg import lu
    P, L, U = lu(A)
    print("Using scipy.linalg.lu:")
    print("P:\n", P)
    print("L:\n", L)
    print("U:\n", U)
except Exception:
    # Doolittle without pivoting (works since A[0,0] != 0)
    n = A.shape[0]
    L = np.eye(n)
    U = np.zeros((n, n))
    for i in range(n):
        for k in range(i, n):
            U[i, k] = A[i, k] - sum(L[i, j] * U[j, k] for j in range(i))
        for k in range(i + 1, n):
            L[k, i] = (A[k, i] - sum(L[k, j] * U[j, i] for j in range(i))) / U[i, i]
    P = np.eye(n)
    print("Using custom Doolittle (no pivot):")
    print("P:\n", P)
    print("L:\n", L)
    print("U:\n", U)

# 验证 PA = LU
print("\nCheck P @ A:\n", P @ A)
print("Check L @ U:\n", L @ U)

Using scipy.linalg.lu:
P:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
L:
 [[ 1.          0.          0.        ]
 [-0.6         1.          0.        ]
 [-0.2         0.18181818  1.        ]]
U:
 [[-5.          2.         -1.        ]
 [ 0.          2.2         5.4       ]
 [ 0.          0.          1.81818182]]

Check P @ A:
 [[-5.  2. -1.]
 [ 3.  1.  6.]
 [ 1.  0.  3.]]
Check L @ U:
 [[-5.00000000e+00  2.00000000e+00 -1.00000000e+00]
 [ 3.00000000e+00  1.00000000e+00  6.00000000e+00]
 [ 1.00000000e+00  2.11951668e-17  3.00000000e+00]]


In [4]:
aList = list(range(2,12))
print("aList:", aList)
print("aList[1:9:2]:", aList[1:9:2])
print("aList[1:-1:2]:", aList[1:-1:2])
print("aList[:3]:", aList[:3])
print("aList[-3:]:", aList[-3:])
print("aList[:]:", aList[:])
print("aList[::]:", aList[::])
print("aList[::-1]:", aList[::-1])
print("aList[9:0:-1]:", aList[9:0:-1])
print("aList[-1:0:-1]:", aList[-1:0:-1])
print("aList[0:100]:", aList[0:100])
print("aList[100:]:", aList[100:])
print("aList[-15:3]:", aList[-15:3])

aList: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
aList[1:9:2]: [3, 5, 7, 9]
aList[1:-1:2]: [3, 5, 7, 9]
aList[:3]: [2, 3, 4]
aList[-3:]: [9, 10, 11]
aList[:]: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
aList[::]: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
aList[::-1]: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2]
aList[9:0:-1]: [11, 10, 9, 8, 7, 6, 5, 4, 3]
aList[-1:0:-1]: [11, 10, 9, 8, 7, 6, 5, 4, 3]
aList[0:100]: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
aList[100:]: []
aList[-15:3]: [2, 3, 4]
