# 草稿本

## 不想开matlab导致的

In [1]:
import numpy as np

A = np.array([[-5, 2, -1],
              [ 1, 0,  3],
              [ 3, 1,  6]], dtype=float)

try:
    from scipy.linalg import lu
    P, L, U = lu(A)
    print("Using scipy.linalg.lu:")
    print("P:\n", P)
    print("L:\n", L)
    print("U:\n", U)
except Exception:
    # Doolittle without pivoting (works since A[0,0] != 0)
    n = A.shape[0]
    L = np.eye(n)
    U = np.zeros((n, n))
    for i in range(n):
        for k in range(i, n):
            U[i, k] = A[i, k] - sum(L[i, j] * U[j, k] for j in range(i))
        for k in range(i + 1, n):
            L[k, i] = (A[k, i] - sum(L[k, j] * U[j, i] for j in range(i))) / U[i, i]
    P = np.eye(n)
    print("Using custom Doolittle (no pivot):")
    print("P:\n", P)
    print("L:\n", L)
    print("U:\n", U)

# 验证 PA = LU
print("\nCheck P @ A:\n", P @ A)
print("Check L @ U:\n", L @ U)

Using scipy.linalg.lu:
P:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
L:
 [[ 1.          0.          0.        ]
 [-0.6         1.          0.        ]
 [-0.2         0.18181818  1.        ]]
U:
 [[-5.          2.         -1.        ]
 [ 0.          2.2         5.4       ]
 [ 0.          0.          1.81818182]]

Check P @ A:
 [[-5.  2. -1.]
 [ 3.  1.  6.]
 [ 1.  0.  3.]]
Check L @ U:
 [[-5.00000000e+00  2.00000000e+00 -1.00000000e+00]
 [ 3.00000000e+00  1.00000000e+00  6.00000000e+00]
 [ 1.00000000e+00  2.11951668e-17  3.00000000e+00]]
